[project]
name = "QOSF_task1"
version = "0.1.0"
description = "QOSF Screening Task1"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "qiskit==2.2.1",
    "qiskit_aer==0.17.1",
    "numpy==2.3.4",
    "pytest",
    "ipykernel"
]